name: printer_client
description: "A local-first, cross-platform material tracking and 3D printer management app."
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management & DI
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  equatable: ^2.0.5

  # Network Layer
  dio: ^5.4.0

  # Storage (Локальне сховище токенів)
  flutter_secure_storage: ^9.0.0

  flutter_staggered_grid_view: ^0.7.0

  dartz: ^0.10.1

  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.5.24

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  drift_dev: ^2.20.0
  build_runner: ^2.4.0

# ==========================================================================
# КОРЕНЕВА СЕКЦІЯ FLUTTER (Має бути строго на початку рядка, без відступів!)
# ==========================================================================
flutter:
  # Системний вказівник для збирача Windows/Linux бінарників
  uses-material-design: true